openapi: 3.0.2
info:
    title: Accounting App Backend Api
    version: '1.0'
servers:
    - url: http://localhost:3002/api
components:
    schemas:
        User:
            $ref: './models/User-schema.yaml#/User'
        Username:
            $ref: './models/User-schema.yaml#/Username'
        Wallet:
            $ref: './models/Wallet-schema.yaml#/Wallet'
        UpdateWallet:
            $ref: './models/Wallet-schema.yaml#/UpdateWallet'
        NewWallet:
            $ref: './models/Wallet-schema.yaml#/NewWallet'
        WalletName:
            $ref: './models/Wallet-schema.yaml#/WalletName'
        WalletId:
            $ref: ./models/Wallet-schema.yaml#/WalletId
        Record:
            $ref: './models/Record-schema.yaml#/Record'
        RecordId:
            $ref: './models/Record-schema.yaml#/RecordId'
        NewRecord:
            $ref: './models/Record-schema.yaml#/NewRecord'
        UpdateRecord:
            $ref: './models/Record-schema.yaml#/UpdateRecord'
        PaginatedRecords:
            $ref: './models/Record-schema.yaml#/PaginatedRecords'
        Category:
            $ref: './models/Category-schema.yaml#/Category'
        NewCategory:
            $ref: './models/Category-schema.yaml#/NewCategory'
        UpdateCategory:
            $ref: './models/Category-schema.yaml#/UpdateCategory'
        CategoryName:
            $ref: './models/Category-schema.yaml#/CategoryName'
        CategoryId:
            $ref: './models/Category-schema.yaml#/CategoryId'
        MessageResult:
            $ref: ./models/MessageResult-schema.yaml#/MessageResult
paths:
    /records:
        $ref: ./paths/records.yaml#/records
    /records/{id}:
        $ref: ./paths/records.yaml#/records~1{id}
    /records/wallet/{walletId}:
        $ref: ./paths/records.yaml#/records~1wallet~1{walletId}
    /records/category/{categoryId}:
        $ref: ./paths/records.yaml#/records~1category~1{categoryId}
    /wallets:
        $ref: ./paths/wallets.yaml#/wallets
    /wallets/{walletId}:
        $ref: ./paths/wallets.yaml#/wallets~1{walletId}
    /categories:
        $ref: ./paths/categories.yaml#/categories
    /categories/{categoryId}:
        $ref: ./paths/categories.yaml#/categories~1{categoryId}
