version: '3.3'
services:
    backend:
        build: .
        ports:
            - 3002:3002
        depends_on: [mysql]
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: direnc_accounting
        ports:
            - 3306:3306
        volumes:
            - db-data:/data
volumes:
    db-data:
