export enum EnvironmentVariables {
  ENVIRONMENT = 'ENVIRONMENT',
  PORT = 'PORT',
  SESSION_SECRET = 'SESSION_SECRET',
  SESSION_MAX_AGE = 'SESSION_MAX_AGE',
  DATABASE_URL = 'DATABASE_URL',
  BACKEND_URL = 'BACKEND_URL',
  MAIL_HOST = 'MAIL_HOST',
  MAIL_PORT = 'MAIL_PORT',
  MAIL_USER = 'MAIL_USER',
  MAIL_PASSWORD = 'MAIL_PASSWORD',
  MAIL_FROM = 'MAIL_FROM',
}
