# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build Project
      run: |
        npm install
        npm run build --if-present
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        # Deployment destination server & path. Formatted as protocol://domain.com:port/full/destination/path/
        ftp-server: sftp://${{ secrets.host }}:${{ secrets.sftpport }}${{ secrets.destination }}
        # FTP account username
        ftp-username: ${{ secrets.username }}
        # FTP account password
        ftp-password: ${{ secrets.password }}
        git-ftp-args: --insecure
    - name: SSH Commands
      uses: appleboy/ssh-action@v0.0.2
      with:
        host: ${{ secrets.host }}
        port: ${{ secrets.sshport }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        script: supervisorctl restart accountingweb
